const MAX_GRN_RECEPTOR_INPUTS: u32 = 16u;
const MAX_GRN_REGULATORY_UNITS: u32 = 16u;
const MAX_GRN_INPUTS_PER_UNIT: u32 = 8u;
const MAX_GRN_STATE_SIZE: u32 = MAX_GRN_RECEPTOR_INPUTS + MAX_GRN_REGULATORY_UNITS;
const MAX_GENES_PER_GENOME: u32 = 200u;
const BASE_PAIRS_PER_GENE: u32 = 20u;
const BASE_PAIRS_PER_GENOME: u32 = MAX_GENES_PER_GENOME * BASE_PAIRS_PER_GENE;
const GENOME_WORD_COUNT: u32 = (BASE_PAIRS_PER_GENOME + 3u) / 4u;
const GRN_EVALUATION_FALLBACK: u32 = 8u;

const DIVISION_PROBABILITY: f32 = 0.0001;
const RANDOM_DEATH_PROBABILITY: f32 = 0.00005;
const LIFEFORM_CAPACITY: u32 = 10000u;
const MIN_DIVISION_ENERGY: f32 = 20.0;

const CELL_EVENT_KIND_DIVISION: u32 = 1u;
const CELL_EVENT_KIND_DEATH: u32 = 2u;
const CELL_EVENT_FLAG_ADHESIVE: u32 = 1u;

const LINK_EVENT_KIND_CREATE: u32 = 1u;
const LINK_EVENT_KIND_REMOVE: u32 = 2u;

const LINK_FLAG_ALIVE: u32 = 1u;
const LINK_FLAG_ADHESIVE: u32 = 1u << 1u;

const LIFEFORM_FLAG_ACTIVE: u32 = 1u;
const LIFEFORM_FLAG_PRESERVED: u32 = 1u << 1u;
const SPECIES_FLAG_ACTIVE: u32 = 1u;

const LIFEFORM_EVENT_KIND_CREATE: u32 = 1u;
const LIFEFORM_EVENT_KIND_DESTROY: u32 = 2u;

const SPECIES_EVENT_KIND_CREATE: u32 = 1u;
const SPECIES_EVENT_KIND_EXTINCT: u32 = 2u;

const MIN_ACTIVE_CELLS: u32 = 20u;
const MUTATE_BASE_CHANCE: f32 = 0.0005;
const SPECIES_DIFF_THRESHOLD: u32 = 200u;
const MAX_SPECIES_CAPACITY: u32 = 1024u;

const HASH_CELL_SIZE: f32 = 8.0;
const COLLISION_EPSILON: f32 = 0.0001;
